version: 2
jobs:
  fetch_and_commit:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            cp VMP_Swaps.csv VMP_Swaps-old.csv

            # Remove heading line and use it to start a new file
            head -n 1 VMP_Swaps-old.csv > VMP_Swaps.csv

            # Get swaps and append to the log
            curl "https://www.vinylmeplease.com/collections/swaps?page=1&view=products-swaps.json" | jq -r '.products[].product | [(.title|sub("\""; "")), .vendor, .price/100] | @csv ' >> VMP_Swaps.csv
            curl "https://www.vinylmeplease.com/collections/swaps?page=2&view=products-swaps.json" | jq -r '.products[].product | [(.title|sub("\""; "")), .vendor, .price/100] | @csv ' >> VMP_Swaps.csv

            git add VMP_Swaps.csv
            git config --global user.email "swapbot@example.com"
            git config --global user.name "SwapBot"
            sudo pip install -r requirements.txt
            csv-diff VMP_Swaps-old.csv VMP_Swaps.csv --key=Title --singular=swap --plural=swaps > message.txt
            echo $'\n[skip ci]' >> message.txt
            git commit -F message.txt && \
              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/sircrumpet/vmp-swaps.git main \
              || true

workflows:
  version: 2
  build:
    jobs:
      - fetch_and_commit
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - fetch_and_commit
